# -*- coding: utf-8 -*-
"""z0.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hUCst3SHwNVqG-l_6RAYdkDSgpLgIynj
"""

# =========================================
# Tabular VEDP_GAN (Latent Diffusion + GAN)
# - Decoder는 "비조건부"(y 미사용)
# - Discriminator/Generator만 y-conditional (AC-GAN 스타일)
# - z0 재구성(MSE/BCE), KL 정규화 포함
# - 합성 시 class 고정(TARGET_CLASS) 또는 원본 비율(p_label) 유지
# =========================================

# ===== Config =====
INPUT_DIR    = "./data"
CSV_FILE     = "WDBC.csv"
CSV_PATH     = __import__("os").path.join(INPUT_DIR, 'original_data', CSV_FILE)

OUTPUT_DIR   = "synth_out"
LABEL_COL    = "diagnosis"

MAX_CAT_UNIQUE = 7
BIN_THRESHOLD  = 0.5


EPOCHS      = 10000
BATCH_SIZE  = 256
LATENT_DIM  = 16
NOISE_DIM   = 16
TIMESTEPS   = 1000
LR          = 1e-3


N_SYNTH      = 1000
TARGET_CLASS = 1     # None이면 원본 비율대로 합성.

# ===== Imports =====
import os, random, numpy as np, pandas as pd
import torch, torch.nn as nn, torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler

# ===== Seed/Device =====
def set_seed(seed=42):
    random.seed(seed); np.random.seed(seed)
    torch.manual_seed(seed); torch.cuda.manual_seed_all(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
set_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ===== Load =====
df = pd.read_csv(CSV_PATH)
assert LABEL_COL in df.columns, f"'{LABEL_COL}' No columns."
y = df[LABEL_COL].astype(int)
X = df.drop(columns=[LABEL_COL])

# ===== 컬럼 타입 자동 분류 =====
num_cols = [c for c in X.columns if np.issubdtype(X[c].dtype, np.number)]
obj_cols = [c for c in X.columns if c not in num_cols]
binary_cols, cat_cols, cont_cols = [], [], []
for c in num_cols:
    vals = pd.unique(X[c].dropna())
    if set(np.unique(vals)).issubset({0,1,0.0,1.0}):
        binary_cols.append(c)
    else:
        if (X[c].dtype.kind in "iu") and (X[c].nunique() <= MAX_CAT_UNIQUE):
            cat_cols.append(c)
        else:
            cont_cols.append(c)
cat_cols += obj_cols

print(f"[INFO] 연속형: {cont_cols}")
print(f"[INFO] 이진형(0/1): {binary_cols}")
print(f"[INFO] 범주형(원-핫): {cat_cols}")
print(f"[INFO] 레이블: {LABEL_COL}")

# ===== 원-핫 인코딩(범주형) =====
X_cat_oh = pd.get_dummies(X[cat_cols], prefix=cat_cols, dummy_na=False) if len(cat_cols)>0 else pd.DataFrame(index=X.index)

# ===== 연속형 표준화 =====
scaler = StandardScaler()
X_cont_scaled = pd.DataFrame(
    scaler.fit_transform(X[cont_cols]) if len(cont_cols)>0 else np.zeros((len(X),0)),
    columns=cont_cols, index=X.index
)

# ===== 이진형은 그대로 =====
X_bin = X[binary_cols].astype(float) if len(binary_cols)>0 else pd.DataFrame(index=X.index)

# ===== cont + (one-hot + binary) =====
X_bin_oh = pd.concat([X_cat_oh, X_bin], axis=1)
X_cont_np = X_cont_scaled.values.astype(np.float32)
X_bin_np  = X_bin_oh.values.astype(np.float32)
y_np      = y.values.astype(np.int64)

# 복원 meta info
oh_info = {
    "cat_cols": cat_cols,
    "oh_columns": list(X_cat_oh.columns),
}
meta = {
    "cont_cols": cont_cols,
    "bin_cols": list(X_bin_oh.columns),
    "label_col": LABEL_COL,
    "orig_bin_cols_only": binary_cols,
}

print("[INFO] input tensor shapes (cont, bin) =", X_cont_np.shape, X_bin_np.shape, "| y shape =", y_np.shape)

# ===== Dataset =====
class TabDataset(Dataset):
    def __init__(self, X_cont_np, X_bin_np, y_np):
        self.Xc = torch.tensor(X_cont_np, dtype=torch.float32)
        self.Xb = torch.tensor(X_bin_np,  dtype=torch.float32)
        self.y  = torch.tensor(y_np,      dtype=torch.long)
        self.Xa = torch.cat([self.Xc, self.Xb], dim=1)  # encoder 입력
    def __len__(self): return len(self.Xa)
    def __getitem__(self, i): return self.Xc[i], self.Xb[i], self.Xa[i], self.y[i]

dl = DataLoader(TabDataset(X_cont_np, X_bin_np, y_np),
                batch_size=BATCH_SIZE, shuffle=True, drop_last=True)

# ===== Model components =====
class Encoder(nn.Module):
    def __init__(self, input_dim, latent_dim):
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Linear(input_dim, 128), nn.ReLU(),
            nn.Linear(128, 64), nn.ReLU(),
        )
        self.fc_mu, self.fc_logvar = nn.Linear(64, latent_dim), nn.Linear(64, latent_dim)
    def forward(self, x):
        h = self.mlp(x)
        mu, logvar = self.fc_mu(h), self.fc_logvar(h)
        std = torch.exp(0.5*logvar); eps = torch.randn_like(std)
        z = mu + eps*std
        return z, mu, logvar

class Diffusion(nn.Module):
    def __init__(self, timesteps=1000, beta_start=1e-4, beta_end=0.02):
        super().__init__()
        betas = np.linspace(beta_start, beta_end, timesteps, dtype=np.float64)
        alphas = 1.0 - betas
        ac = np.cumprod(alphas)
        self.timesteps = timesteps
        self.register_buffer("sqrt_ac",     torch.tensor(np.sqrt(ac), dtype=torch.float32))
        self.register_buffer("sqrt_1m_ac",  torch.tensor(np.sqrt(1.0 - ac), dtype=torch.float32))
    def forward(self, z0):
        B = z0.size(0)
        t = torch.randint(0, self.timesteps, (B,), device=z0.device)
        a, b = self.sqrt_ac[t].unsqueeze(1), self.sqrt_1m_ac[t].unsqueeze(1)
        noise = torch.randn_like(z0)
        zt = a*z0 + b*noise
        return zt, t

class Discriminator(nn.Module):
    """AC-GAN: adv(real/fake) + cls(label) head. t, y use embedding."""
    def __init__(self, latent_dim, timesteps=1000, t_emb_dim=16, y_emb_dim=4):
        super().__init__()
        self.t_emb = nn.Embedding(timesteps, t_emb_dim)
        self.y_emb = nn.Embedding(2, y_emb_dim)
        in_dim = latent_dim + t_emb_dim + y_emb_dim
        self.shared = nn.Sequential(nn.Linear(in_dim, 64), nn.ReLU())
        self.adv_head = nn.Linear(64, 1)
        self.cls_head = nn.Linear(64, 2)
    def forward(self, z, t, y):
        te = self.t_emb(t)
        ye = self.y_emb(y)
        h  = torch.cat([z, te, ye], dim=1)
        h  = self.shared(h)
        return self.adv_head(h), self.cls_head(h)

class Generator(nn.Module):
    def __init__(self, noise_dim, latent_dim, timesteps=1000, t_emb_dim=16, y_emb_dim=4):
        super().__init__()
        self.t_emb = nn.Embedding(timesteps, t_emb_dim)
        self.y_emb = nn.Embedding(2, y_emb_dim)
        self.net = nn.Sequential(
            nn.Linear(noise_dim + t_emb_dim + y_emb_dim, 64), nn.ReLU(),
            nn.Linear(64, latent_dim)
        )
        self.noise_dim, self.timesteps = noise_dim, timesteps
    def forward(self, noise, t, y):
        te = self.t_emb(t)
        ye = self.y_emb(y)
        h  = torch.cat([noise, te, ye], dim=1)
        return self.net(h)

class DecoderMixed(nn.Module):
    """비조건부 Decoder: z -> (x_cont, x_bin_logit)"""
    def __init__(self, latent_dim, cont_dim, bin_dim):
        super().__init__()
        self.shared = nn.Sequential(nn.Linear(latent_dim, 64), nn.ReLU())
        self.hc = nn.Linear(64, cont_dim) if cont_dim>0 else None
        self.hb = nn.Linear(64, bin_dim)  if bin_dim>0  else None
    def forward(self, z):
        h = self.shared(z)
        out = {}
        if self.hc is not None:
            out["x_hat_cont"] = self.hc(h)
        if self.hb is not None:
            out["x_hat_bin_logit"] = self.hb(h)
        return out

class VEDP_GANMixed(nn.Module):
    def __init__(self, cont_dim, bin_dim, latent_dim, noise_dim, timesteps=1000):
        super().__init__()
        in_dim = cont_dim + bin_dim
        self.cont_dim, self.bin_dim = cont_dim, bin_dim
        self.encoder = Encoder(in_dim, latent_dim)
        self.diffusion = Diffusion(timesteps)
        self.generator = Generator(noise_dim, latent_dim, timesteps)
        self.discriminator = Discriminator(latent_dim, timesteps)
        self.decoder = DecoderMixed(latent_dim, cont_dim, bin_dim)
        self.noise_dim, self.timesteps = noise_dim, timesteps
    def sample_noise(self, n, device): return torch.randn(n, self.noise_dim, device=device)

# ===== Loss / Optim =====
mse = nn.MSELoss()
bce_logits = nn.BCEWithLogitsLoss()
def kl_loss(mu, logvar):
    return 0.5 * torch.mean(torch.exp(logvar) + mu**2 - 1.0 - logvar)

C, B = X_cont_np.shape[1], X_bin_np.shape[1]
model = VEDP_GANMixed(C, B, latent_dim=LATENT_DIM, noise_dim=NOISE_DIM, timesteps=TIMESTEPS).to(device)

# ===== Z0 버전 학습 루틴 (Decoder는 비조건부) =====
def _train_model_z0(
    model, dl, device, *, epochs=30, lr=1e-3,
    w_rec=1.0, w_kl=0.01, w_cls=1.0
):
    """
    Z0: D(real)=z0(latent), D(fake)=Generator(noise,y).
    """
    mse = nn.MSELoss()
    bce_logits = nn.BCEWithLogitsLoss()
    ce = nn.CrossEntropyLoss()

    def kl_loss(mu, logvar):
        return 0.5 * torch.mean(torch.exp(logvar) + mu**2 - 1.0 - logvar)

    opt_encdec = torch.optim.Adam(
        list(model.encoder.parameters()) + list(model.decoder.parameters()), lr=lr
    )
    opt_g = torch.optim.Adam(model.generator.parameters(), lr=lr, betas=(0.5, 0.999))
    opt_d = torch.optim.Adam(model.discriminator.parameters(), lr=lr, betas=(0.5, 0.999))

    C, B = model.cont_dim, model.bin_dim
    model.train()

    for epoch in range(1, epochs+1):
        running = {"d":0.0, "g":0.0, "rec":0.0, "kl":0.0}
        for Xc, Xb, Xa, yb in dl:
            Xc, Xb, Xa, yb = Xc.to(device), Xb.to(device), Xa.to(device), yb.to(device)


            z0, mu, logvar = model.encoder(Xa)


            noise = model.sample_noise(Xa.size(0), Xa.device)

            t = torch.zeros(Xa.size(0), dtype=torch.long, device=device)
            z0_fake = model.generator(noise, t, yb)


            dec = model.decoder(z0)
            loss_rec = 0.0
            if C > 0:
                loss_rec += mse(dec["x_hat_cont"], Xc)
            if B > 0:
                loss_rec += bce_logits(dec["x_hat_bin_logit"], Xb)
            loss_kl = w_kl * kl_loss(mu, logvar)


            adv_r, cls_r = model.discriminator(z0.detach(), t, yb)
            adv_f, cls_f = model.discriminator(z0_fake.detach(), t, yb)
            loss_d = (
                bce_logits(adv_r, torch.ones_like(adv_r)) +
                bce_logits(adv_f, torch.zeros_like(adv_f)) +
                w_cls * ce(cls_r, yb)
            )
            opt_d.zero_grad()
            loss_d.backward()
            opt_d.step()


            adv_f_g, cls_f_g = model.discriminator(z0_fake, t, yb)
            loss_g = bce_logits(adv_f_g, torch.ones_like(adv_f_g)) + w_cls * ce(cls_f_g, yb)

            opt_encdec.zero_grad()
            opt_g.zero_grad()
            (w_rec * loss_rec + loss_kl + loss_g).backward()
            opt_encdec.step()
            opt_g.step()

            running["d"]  += float(loss_d.item())
            running["g"]  += float(loss_g.item())
            running["rec"]+= float(loss_rec.item() if isinstance(loss_rec, torch.Tensor) else 0.0)
            running["kl"] += float(loss_kl.item() if isinstance(loss_kl, torch.Tensor) else 0.0)

        n_batches = max(1, len(dl))
        
        if epoch % 100 == 0:
            print(f"[Epoch {epoch:03d}] D:{running['d']/n_batches:.4f} | G:{running['g']/n_batches:.4f} | "
                f"REC:{running['rec']/n_batches:.4f} | KL:{running['kl']/n_batches:.4f}")


# ===== Train =====
_train_model_z0(model, dl, device, epochs=EPOCHS, lr=LR, w_rec=1.0, w_kl=0.01, w_cls=1.0)

# ===== Synthesize =====
@torch.no_grad()
def synthesize_conditional(model, n_samples, target_class=None, p_label=None, bin_threshold=BIN_THRESHOLD):
    model.eval()

    if target_class is None:
        if p_label is None:
            raise ValueError("p_label이 None입니다. 원본 비율을 쓰려면 p_label을 주세요.")
        y_fake = torch.bernoulli(torch.full((n_samples,), float(p_label), device=device)).long()
    else:
        y_fake = torch.full((n_samples,), int(target_class), device=device, dtype=torch.long)

    t = torch.randint(0, model.timesteps, (n_samples,), device=device)
    noise = torch.randn(n_samples, model.noise_dim, device=device)
    z = model.generator(noise, t, y_fake)
    dec = model.decoder(z)

    cont_df = pd.DataFrame()
    if C>0:
        cont_np = dec["x_hat_cont"].cpu().numpy()
        cont_np = scaler.inverse_transform(cont_np)
        cont_df = pd.DataFrame(cont_np, columns=meta["cont_cols"])

    bin_df = pd.DataFrame()
    if B>0:
        prob = torch.sigmoid(dec["x_hat_bin_logit"]).cpu().numpy()
        bin_np = (prob >= bin_threshold).astype(float)
        bin_df = pd.DataFrame(bin_np, columns=meta["bin_cols"])


    cat_out = {}
    for c in oh_info["cat_cols"]:
        cols = [col for col in oh_info["oh_columns"] if col.startswith(c + "_")]
        if len(cols)==0: continue
        arg = bin_df[cols].values.argmax(axis=1)
        levels = [col[len(c)+1:] for col in cols]
        cat_out[c] = [levels[i] for i in arg]
        bin_df.drop(columns=cols, inplace=True, errors="ignore")

    out_df = pd.concat([cont_df, bin_df], axis=1)
    if cat_out: out_df = pd.concat([out_df, pd.DataFrame(cat_out)], axis=1)


    out_df[LABEL_COL] = y_fake.cpu().numpy().astype(int)


    for c in meta["orig_bin_cols_only"]:
        if c in out_df.columns:
            out_df[c] = out_df[c].round().astype(int)
    return out_df

p_label = float(y.mean())
synth_df = synthesize_conditional(model, n_samples=N_SYNTH, target_class=TARGET_CLASS, p_label=p_label, bin_threshold=BIN_THRESHOLD)

out_name = f"synth_{os.path.splitext(os.path.basename(CSV_PATH))[0]}_{'all' if TARGET_CLASS is None else f'class{TARGET_CLASS}'}_{N_SYNTH}.csv"
OUT_PATH = os.path.join(OUTPUT_DIR, out_name)
synth_df.to_csv(OUT_PATH, index=False)
print("Saved:", OUT_PATH, "| class-1 ratio:", synth_df[LABEL_COL].mean(), "(target~", (p_label if TARGET_CLASS is None else TARGET_CLASS), ")")